name: CI Pipeline

on:
  pull_request:
    branches:
      - main  # This ensures the action runs on pull requests to the `main` branch

jobs:
  test:
    runs-on: ubuntu-latest  # You can also use other environments like macOS or Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Specify the Python version you want

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest  # Or any other testing command you use